
USE MZAsistencial;
GO

EXEC sp_MSforeachtable "ALTER TABLE ? NOCHECK CONSTRAINT ALL";
GO
SET IDENTITY_INSERT [dbo].[ICG06] ON;
INSERT INTO [dbo].[ICG06] ([Id_ICG],[Año],[Centro_id],[GasfinAG],[GasfinASCC],[GasfinASCP],[GasfinCIT],[GasfinPSS],[Actidesde],[Actihasta],[Validado],[FechaModificacion],[FechaAlta],[UsuarioAlta_id],[UsuarioModificacion_id]) VALUES (1,2024,1,45000.00,120000.00,850000.00,80000.00,95000.00,'20240101 00:00:00','20241231 00:00:00',0,NULL,'20240315 00:00:00',2,NULL);
INSERT INTO [dbo].[ICG06] ([Id_ICG],[Año],[Centro_id],[GasfinAG],[GasfinASCC],[GasfinASCP],[GasfinCIT],[GasfinPSS],[Actidesde],[Actihasta],[Validado],[FechaModificacion],[FechaAlta],[UsuarioAlta_id],[UsuarioModificacion_id]) VALUES (2,2024,2,38000.00,0.00,980000.00,70000.00,85000.00,'20240101 00:00:00','20241231 00:00:00',0,NULL,'20240315 00:00:00',2,NULL);
SET IDENTITY_INSERT [dbo].[ICG06] OFF;
SET IDENTITY_INSERT [dbo].[ICG07] ON;
INSERT INTO [dbo].[ICG07] ([Id_ICG], [Año], [Concierto_id], [Especialid], [Fautorizacion], [Fsuscrip], [Fresoluc], [Fprorroga], [FinVigencia], [Muniambito], [Costeassan], [CosteIT], [CostePRL], [TipConciert], [Provincia], [Localid], [CP], [Ubicac], [PAsinurg], [PAurgencias], [Pingresadas], [ASAMprimconsProg], [ASAMconssuc], [ASAMsesrehab], [ASAMplacrad(RADIO)], [ASAMintquir], [ASAMintquirmp], [ASAMotrasprueb], [ASHNprimconsProg], [ASHNconssuc], [ASHNestcaus], [ASHNsesrehab], [ASHNplacrad(RADIO)], [ASHNintquir], [ASHNintquirmp], [ASHNotrasprueb], [CITnºconsesp], [CITnºsesrehab], [CITnºintquir], [CITnºotrpru], [Dista25km], [Dista25-50km], [Masde50km], [Persfisica], [Persjurpriv], [Persjursist], [PersjurOSP], [PersjurOmutua], [Art2581], [Art2582], [RestoArticulo25SCon], [GastoCentroNoConcert], [Validado], [UsuarioAlta_id], [FechaAlta], [UsuarioModificacion_id], [FechaModificacion], [ICG07_2014], [Agrupacion_id], [ASAMprimconsProg(Video)], [ASAMprimconsNoProg], [ASAMprimconsNoProg(Video)], [ASAMconssuc(Video)], [ASAMconseenf], [ASAMestcaus], [ASAMplacrad(RM)], [ASAMplacrad(Eco)], [ASAMplacrad(TAC)], [ASHNprimconsProg(video)], [ASHNprimconsNoProg], [ASHNprimconsNoProg(video)], [ASHNconssuc(video)], [ASHNplacrad(RM)], [ASHNplacrad(Eco)], [ASHNplacrad(TAC)], [ASAMBiomec], [ASHNBiomec], [CITNIntervencionesQuirurjicas], [CITNOtrasPruebasControl], [ASHNConsultasEnfermeria], [GastoTransporte]) VALUES (1,2024,1,'Traumatología y Cirugía Ortopédica','20240101 00:00:00',NULL,NULL,NULL,NULL,NULL,85.50,0.00,NULL,1,'Barcelona','Badalona',NULL,NULL,0,0,0,120,240,200,NULL,20,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,0,0,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,2,'20240315 00:00:00',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO [dbo].[ICG07] ([Id_ICG], [Año], [Concierto_id], [Especialid], [Fautorizacion], [Fsuscrip], [Fresoluc], [Fprorroga], [FinVigencia], [Muniambito], [Costeassan], [CosteIT], [CostePRL], [TipConciert], [Provincia], [Localid], [CP], [Ubicac], [PAsinurg], [PAurgencias], [Pingresadas], [ASAMprimconsProg], [ASAMconssuc], [ASAMsesrehab], [ASAMplacrad(RADIO)], [ASAMintquir], [ASAMintquirmp], [ASAMotrasprueb], [ASHNprimconsProg], [ASHNconssuc], [ASHNestcaus], [ASHNsesrehab], [ASHNplacrad(RADIO)], [ASHNintquir], [ASHNintquirmp], [ASHNotrasprueb], [CITnºconsesp], [CITnºsesrehab], [CITnºintquir], [CITnºotrpru], [Dista25km], [Dista25-50km], [Masde50km], [Persfisica], [Persjurpriv], [Persjursist], [PersjurOSP], [PersjurOmutua], [Art2581], [Art2582], [RestoArticulo25SCon], [GastoCentroNoConcert], [Validado], [UsuarioAlta_id], [FechaAlta], [UsuarioModificacion_id], [FechaModificacion], [ICG07_2014], [Agrupacion_id], [ASAMprimconsProg(Video)], [ASAMprimconsNoProg], [ASAMprimconsNoProg(Video)], [ASAMconssuc(Video)], [ASAMconseenf], [ASAMestcaus], [ASAMplacrad(RM)], [ASAMplacrad(Eco)], [ASAMplacrad(TAC)], [ASHNprimconsProg(video)], [ASHNprimconsNoProg], [ASHNprimconsNoProg(video)], [ASHNconssuc(video)], [ASHNplacrad(RM)], [ASHNplacrad(Eco)], [ASHNplacrad(TAC)], [ASAMBiomec], [ASHNBiomec], [CITNIntervencionesQuirurjicas], [CITNOtrasPruebasControl], [ASHNConsultasEnfermeria], [GastoTransporte]) VALUES (2,2024,2,'Rehabilitación y Fisioterapia','20240101 00:00:00',NULL,NULL,NULL,NULL,NULL,40.00,0.00,NULL,1,'Valencia','Paterna',NULL,NULL,0,0,0,0,0,200,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,0,0,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,3,'20240315 00:00:00',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
SET IDENTITY_INSERT [dbo].[ICG07] OFF;


SET IDENTITY_INSERT [dbo].[Mutuas] ON;
INSERT INTO [dbo].[Mutuas] ([Mutua_id], [NumeroMutua], [Mutua], [RazonSocial], [Direccion], [CP], [Poblacion_id], [Telefono], [Fax], [DireccionElectronica], [PersonaContacto], [Logotipo], [FechaAlta], [UsuarioAlta_id], [FechaModificacion], [UsuarioModificacion_id], [FechaBaja], [UsuarioBaja_id], [RatioConsultas], [Usuario_id]) VALUES (1,'M01','Mutualia','Mutualia Mutua Colaboradora de la SS','Calle del Salvador, 14','28013',8,'913 421 800    ','913 421 801    ','contacto@mutualia.es','Carlos Martínez Gil',NULL,'2020-01-10 00:00:00',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO [dbo].[Mutuas] ([Mutua_id], [NumeroMutua], [Mutua], [RazonSocial], [Direccion], [CP], [Poblacion_id], [Telefono], [Fax], [DireccionElectronica], [PersonaContacto], [Logotipo], [FechaAlta], [UsuarioAlta_id], [FechaModificacion], [UsuarioModificacion_id], [FechaBaja], [UsuarioBaja_id], [RatioConsultas], [Usuario_id]) VALUES (2,'M02','Prevensalud','Prevensalud Mutua Colaboradora de la SS','Avenida de los Naranjos, 8','08029',5,'932 180 500    ','932 180 501    ','contacto@prevensalud.es','Laura Sánchez Ruiz',NULL,'20200215 00:00:00',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO [dbo].[Mutuas] ([Mutua_id], [NumeroMutua], [Mutua], [RazonSocial], [Direccion], [CP], [Poblacion_id], [Telefono], [Fax], [DireccionElectronica], [PersonaContacto], [Logotipo], [FechaAlta], [UsuarioAlta_id], [FechaModificacion], [UsuarioModificacion_id], [FechaBaja], [UsuarioBaja_id], [RatioConsultas], [Usuario_id]) VALUES (3,'M03','Nexomutua','Nexomutua Mutua Colaboradora de la SS','Paseo de la Alameda, 3','08029',5,'934 390 700    ','934 390 701    ','contacto@nexomutua.es','Pedro Gómez Torres',NULL,'20200203 00:00:00',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO [dbo].[Mutuas] ([Mutua_id], [NumeroMutua], [Mutua], [RazonSocial], [Direccion], [CP], [Poblacion_id], [Telefono], [Fax], [DireccionElectronica], [PersonaContacto], [Logotipo], [FechaAlta], [UsuarioAlta_id], [FechaModificacion], [UsuarioModificacion_id], [FechaBaja], [UsuarioBaja_id], [RatioConsultas], [Usuario_id]) VALUES (4,'M04','Laboralia','Laboralia Mutua Colaboradora de la SS','Calle del Pinar, 22','28009',8,'914 502 300    ','914 502 301    ','contacto@laboralia.es','Ana Rodríguez Vega',NULL,'2020-04-01 00:00:00',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO [dbo].[Mutuas] ([Mutua_id], [NumeroMutua], [Mutua], [RazonSocial], [Direccion], [CP], [Poblacion_id], [Telefono], [Fax], [DireccionElectronica], [PersonaContacto], [Logotipo], [FechaAlta], [UsuarioAlta_id], [FechaModificacion], [UsuarioModificacion_id], [FechaBaja], [UsuarioBaja_id], [RatioConsultas], [Usuario_id]) VALUES (5,'M05','Salumut','Salumut Mutua Colaboradora de la SS','Calle de la Encina, 5','08007',5,'935 210 900    ','935 210 901    ','contacto@salumut.es','Javier López Moreno',NULL,'2020-05-10 00:00:00',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
SET IDENTITY_INSERT [dbo].[Mutuas] OFF;

DBCC CHECKIDENT ('dbo.Mutuas', RESEED, 5);


PRINT 'Carga completada';
